alias ..='cd ..'
alias apti='sudo apt install'
alias aptup='sudo apt update && sudo apt upgrade'
alias aptar='sudo apt autoremove'
alias ls='exa -l --icons'
alias clear='clear figlet avdzm | lolcat && colorscript -r'
alias surf='tabbed surf -e'
alias torrent='/home/avdzm/.rofi_scripts/rofi_xtorrent.v1.sh'
alias wget='wget -c'
alias df='df -h'
alias free='free -h'
alias vifm='~/.config/vifm/scripts/vifmrun'
export EDITOR=vim
export BROWSER=surf
